# Generated by Django 3.2.13 on 2022-11-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20221120_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
