# Generated by Django 3.2.13 on 2022-11-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.TextField(default='', null=True),
        ),
    ]
